INSERT INTO `departamentos` (`id`, `nombre`) VALUES
(null, 'ANTIOQUIA'),
(null, 'ATLANTICO'),
(null, 'D.C.'),
(null, 'BOLIVAR'),
(null, 'BOYACA'),
(null, 'CALDAS'),
(null, 'CAQUETA'),
(null, 'CAUCA'),
(null, 'CESAR'),
(null, 'CORDOBA'),
(null, 'CUNDINAMARCA'),
(null, 'CHOCO'),
(null, 'HUILA'),
(null, 'LA GUAJIRA'),
(null, 'MAGDALENA'),
(null, 'META'),
(null, 'NARIÑO'),
(null, 'N. DE SANTANDER'),
(null, 'QUINDIO'),
(null, 'RISARALDA'),
(null, 'SANTANDER'),
(null, 'SUCRE'),
(null, 'TOLIMA'),
(null, 'VALLE DEL CAUCA'),
(null, 'ARAUCA'),
(null, 'CASANARE'),
(null, 'PUTUMAYO'),
(null, 'SAN ANDRES'),
(null, 'AMAZONAS'),
(null, 'GUAINIA'),
(null, 'GUAVIARE'),
(null, 'VAUPES'),
(null, 'VICHADA');



INSERT INTO `municipios` (`id`, `departamento_id`, `nombre`) VALUES
(null, 1, 'MEDELLIN'),
(null, 1, 'ABEJORRAL'),
(null, 1, 'ABRIAQUI'),
(null, 1, 'ALEJANDRIA'),
(null, 1, 'AMAGA'),
(null, 1, 'AMALFI'),
(null, 1, 'ANDES'),
(null, 1, 'ANGELOPOLIS'),
(null, 1, 'ANGOSTURA'),
(null, 1, 'ANORI'),
(null, 1, 'SANTAFE DE ANTIOQUIA'),
(null, 1, 'ANZA'),
(null, 1, 'APARTADO'),
(null, 1, 'ARBOLETES'),
(null, 1, 'ARGELIA'),
(null, 1, 'ARMENIA'),
(null, 1, 'BARBOSA'),
(null, 1, 'BELMIRA'),
(null, 1, 'BELLO'),
(null, 1, 'BETANIA'),
(null, 1, 'BETULIA'),
(null, 1, 'CIUDAD BOLIVAR'),
(null, 1, 'BRICEÑO'),
(null, 1, 'BURITICA'),
(null, 1, 'CACERES'),
(null, 1, 'CAICEDO'),
(null, 1, 'CALDAS'),
(null, 1, 'CAMPAMENTO'),
(null, 1, 'CAÑASGORDAS'),
(null, 1, 'CARACOLI'),
(null, 1, 'CARAMANTA'),
(null, 1, 'CAREPA'),
(null, 1, 'EL CARMEN DE VIBORAL'),
(null, 1, 'CAROLINA'),
(null, 1, 'CAUCASIA'),
(null, 1, 'CHIGORODO'),
(null, 1, 'CISNEROS'),
(null, 1, 'COCORNA'),
(null, 1, 'CONCEPCION'),
(null, 1, 'CONCORDIA'),
(null, 1, 'COPACABANA'),
(null, 1, 'DABEIBA'),
(null, 1, 'DON MATIAS'),
(null, 1, 'EBEJICO'),
(null, 1, 'EL BAGRE'),
(null, 1, 'ENTRERRIOS'),
(null, 1, 'ENVIGADO'),
(null, 1, 'FREDONIA'),
(null, 1, 'FRONTINO'),
(null, 1, 'GIRALDO'),
(null, 1, 'GIRARDOTA'),
(null, 1, 'GOMEZ PLATA'),
(null, 1, 'GRANADA'),
(null, 1, 'GUADALUPE'),
(null, 1, 'GUARNE'),
(null, 1, 'GUATAPE'),
(null, 1, 'HELICONIA'),
(null, 1, 'HISPANIA'),
(null, 1, 'ITAGUI'),
(null, 1, 'ITUANGO'),
(null, 1, 'JARDIN'),
(null, 1, 'JERICO'),
(null, 1, 'LA CEJA'),
(null, 1, 'LA ESTRELLA'),
(null, 1, 'LA PINTADA'),
(null, 1, 'LA UNION'),
(null, 1, 'LIBORINA'),
(null, 1, 'MACEO'),
(null, 1, 'MARINILLA'),
(null, 1, 'MONTEBELLO'),
(null, 1, 'MURINDO'),
(null, 1, 'MUTATA'),
(null, 1, 'NARIÑO'),
(null, 1, 'NECOCLI'),
(null, 1, 'NECHI'),
(null, 1, 'OLAYA'),
(null, 1, 'PEÑOL'),
(null, 1, 'PEQUE'),
(null, 1, 'PUEBLORRICO'),
(null, 1, 'PUERTO BERRIO'),
(null, 1, 'PUERTO NARE'),
(null, 1, 'PUERTO TRIUNFO'),
(null, 1, 'REMEDIOS'),
(null, 1, 'RETIRO'),
(null, 1, 'RIONEGRO'),
(null, 1, 'SABANALARGA'),
(null, 1, 'SABANETA'),
(null, 1, 'SALGAR'),
(null, 1, 'SAN ANDRES DE CUERQUIA'),
(null, 1, 'SAN CARLOS'),
(null, 1, 'SAN FRANCISCO'),
(null, 1, 'SAN JERONIMO'),
(null, 1, 'SAN JOSE DE LA MONTAÑA'),
(null, 1, 'SAN JUAN DE URABA'),
(null, 1, 'SAN LUIS'),
(null, 1, 'SAN PEDRO'),
(null, 1, 'SAN PEDRO DE URABA'),
(null, 1, 'SAN RAFAEL'),
(null, 1, 'SAN ROQUE'),
(null, 1, 'SAN VICENTE'),
(null, 1, 'SANTA BARBARA'),
(null, 1, 'SANTA ROSA DE OSOS'),
(null, 1, 'SANTO DOMINGO'),
(null, 1, 'EL SANTUARIO'),
(null, 1, 'SEGOVIA'),
(null, 1, 'SONSON'),
(null, 1, 'SOPETRAN'),
(null, 1, 'TAMESIS'),
(null, 1, 'TARAZA'),
(null, 1, 'TARSO'),
(null, 1, 'TITIRIBI'),
(null, 1, 'TOLEDO'),
(null, 1, 'TURBO'),
(null, 1, 'URAMITA'),
(null, 1, 'URRAO'),
(null, 1, 'VALDIVIA'),
(null, 1, 'VALPARAISO'),
(null, 1, 'VEGACHI'),
(null, 1, 'VENECIA'),
(null, 1, 'VIGIA DEL FUERTE'),
(null, 1, 'YALI'),
(null, 1, 'YARUMAL'),
(null, 1, 'YOLOMBO'),
(null, 1, 'YONDO'),
(null, 1, 'ZARAGOZA'),
(null, 2, 'BARRANQUILLA'),
(null, 2, 'BARANOA'),
(null, 2, 'CAMPO DE LA CRUZ'),
(null, 2, 'CANDELARIA'),
(null, 2, 'GALAPA'),
(null, 2, 'JUAN DE ACOSTA'),
(null, 2, 'LURUACO'),
(null, 2, 'MALAMBO'),
(null, 2, 'MANATI'),
(null, 2, 'PALMAR DE VARELA'),
(null, 2, 'PIOJO'),
(null, 2, 'POLONUEVO'),
(null, 2, 'PONEDERA'),
(null, 2, 'PUERTO COLOMBIA'),
(null, 2, 'REPELON'),
(null, 2, 'SABANAGRANDE'),
(null, 2, 'SABANALARGA'),
(null, 2, 'SANTA LUCIA'),
(null, 2, 'SANTO TOMAS'),
(null, 2, 'SOLEDAD'),
(null, 2, 'SUAN'),
(null, 2, 'TUBARA'),
(null, 2, 'USIACURI'),
(null, 3, 'BOGOTA'),
(null, 4, 'CARTAGENA'),
(null, 4, 'ACHI'),
(null, 4, 'ALTOS DEL ROSARIO'),
(null, 4, 'ARENAL'),
(null, 4, 'ARJONA'),
(null, 4, 'ARROYOHONDO'),
(null, 4, 'BARRANCO DE LOBA'),
(null, 4, 'CALAMAR'),
(null, 4, 'CANTAGALLO'),
(null, 4, 'CICUCO'),
(null, 4, 'CORDOBA'),
(null, 4, 'CLEMENCIA'),
(null, 4, 'EL CARMEN DE BOLIVAR'),
(null, 4, 'EL GUAMO'),
(null, 4, 'EL PEÑON'),
(null, 4, 'HATILLO DE LOBA'),
(null, 4, 'MAGANGUE'),
(null, 4, 'MAHATES'),
(null, 4, 'MARGARITA'),
(null, 4, 'MARIA LA BAJA'),
(null, 4, 'MONTECRISTO'),
(null, 4, 'MOMPOS'),
(null, 4, 'NOROSI'),
(null, 4, 'MORALES'),
(null, 4, 'PINILLOS'),
(null, 4, 'REGIDOR'),
(null, 4, 'RIO VIEJO'),
(null, 4, 'SAN CRISTOBAL'),
(null, 4, 'SAN ESTANISLAO'),
(null, 4, 'SAN FERNANDO'),
(null, 4, 'SAN JACINTO'),
(null, 4, 'SAN JACINTO DEL CAUCA'),
(null, 4, 'SAN JUAN NEPOMUCENO'),
(null, 4, 'SAN MARTIN DE LOBA'),
(null, 4, 'SAN PABLO'),
(null, 4, 'SANTA CATALINA'),
(null, 4, 'SANTA ROSA'),
(null, 4, 'SANTA ROSA DEL SUR'),
(null, 4, 'SIMITI'),
(null, 4, 'SOPLAVIENTO'),
(null, 4, 'TALAIGUA NUEVO'),
(null, 4, 'TIQUISIO'),
(null, 4, 'TURBACO'),
(null, 4, 'TURBANA'),
(null, 4, 'VILLANUEVA'),
(null, 4, 'ZAMBRANO'),
(null, 5, 'TUNJA'),
(null, 5, 'ALMEIDA'),
(null, 5, 'AQUITANIA'),
(null, 5, 'ARCABUCO'),
(null, 5, 'BELEN'),
(null, 5, 'BERBEO'),
(null, 5, 'BETEITIVA'),
(null, 5, 'BOAVITA'),
(null, 5, 'BOYACA'),
(null, 5, 'BRICEÑO'),
(null, 5, 'BUENAVISTA'),
(null, 5, 'BUSBANZA'),
(null, 5, 'CALDAS'),
(null, 5, 'CAMPOHERMOSO'),
(null, 5, 'CERINZA'),
(null, 5, 'CHINAVITA'),
(null, 5, 'CHIQUINQUIRA'),
(null, 5, 'CHISCAS'),
(null, 5, 'CHITA'),
(null, 5, 'CHITARAQUE'),
(null, 5, 'CHIVATA'),
(null, 5, 'CIENEGA'),
(null, 5, 'COMBITA'),
(null, 5, 'COPER'),
(null, 5, 'CORRALES'),
(null, 5, 'COVARACHIA'),
(null, 5, 'CUBARA'),
(null, 5, 'CUCAITA'),
(null, 5, 'CUITIVA'),
(null, 5, 'CHIQUIZA'),
(null, 5, 'CHIVOR'),
(null, 5, 'DUITAMA'),
(null, 5, 'EL COCUY'),
(null, 5, 'EL ESPINO'),
(null, 5, 'FIRAVITOBA'),
(null, 5, 'FLORESTA'),
(null, 5, 'GACHANTIVA'),
(null, 5, 'GAMEZA'),
(null, 5, 'GARAGOA'),
(null, 5, 'GUACAMAYAS'),
(null, 5, 'GUATEQUE'),
(null, 5, 'GUAYATA'),
(null, 5, 'GsICAN'),
(null, 5, 'IZA'),
(null, 5, 'JENESANO'),
(null, 5, 'JERICO'),
(null, 5, 'LABRANZAGRANDE'),
(null, 5, 'LA CAPILLA'),
(null, 5, 'LA VICTORIA'),
(null, 5, 'LA UVITA'),
(null, 5, 'VILLA DE LEYVA'),
(null, 5, 'MACANAL'),
(null, 5, 'MARIPI'),
(null, 5, 'MIRAFLORES'),
(null, 5, 'MONGUA'),
(null, 5, 'MONGUI'),
(null, 5, 'MONIQUIRA'),
(null, 5, 'MOTAVITA'),
(null, 5, 'MUZO'),
(null, 5, 'NOBSA'),
(null, 5, 'NUEVO COLON'),
(null, 5, 'OICATA'),
(null, 5, 'OTANCHE'),
(null, 5, 'PACHAVITA'),
(null, 5, 'PAEZ'),
(null, 5, 'PAIPA'),
(null, 5, 'PAJARITO'),
(null, 5, 'PANQUEBA'),
(null, 5, 'PAUNA'),
(null, 5, 'PAYA'),
(null, 5, 'PAZ DE RIO'),
(null, 5, 'PESCA'),
(null, 5, 'PISBA'),
(null, 5, 'PUERTO BOYACA'),
(null, 5, 'QUIPAMA'),
(null, 5, 'RAMIRIQUI'),
(null, 5, 'RAQUIRA'),
(null, 5, 'RONDON'),
(null, 5, 'SABOYA'),
(null, 5, 'SACHICA'),
(null, 5, 'SAMACA'),
(null, 5, 'SAN EDUARDO'),
(null, 5, 'SAN JOSE DE PARE'),
(null, 5, 'SAN LUIS DE GACENO'),
(null, 5, 'SAN MATEO'),
(null, 5, 'SAN MIGUEL DE SEMA'),
(null, 5, 'SAN PABLO DE BORBUR'),
(null, 5, 'SANTANA'),
(null, 5, 'SANTA MARIA'),
(null, 5, 'SANTA ROSA DE VITERBO'),
(null, 5, 'SANTA SOFIA'),
(null, 5, 'SATIVANORTE'),
(null, 5, 'SATIVASUR'),
(null, 5, 'SIACHOQUE'),
(null, 5, 'SOATA'),
(null, 5, 'SOCOTA'),
(null, 5, 'SOCHA'),
(null, 5, 'SOGAMOSO'),
(null, 5, 'SOMONDOCO'),
(null, 5, 'SORA'),
(null, 5, 'SOTAQUIRA'),
(null, 5, 'SORACA'),
(null, 5, 'SUSACON'),
(null, 5, 'SUTAMARCHAN'),
(null, 5, 'SUTATENZA'),
(null, 5, 'TASCO'),
(null, 5, 'TENZA'),
(null, 5, 'TIBANA'),
(null, 5, 'TIBASOSA'),
(null, 5, 'TINJACA'),
(null, 5, 'TIPACOQUE'),
(null, 5, 'TOCA'),
(null, 5, 'TOGsI'),
(null, 5, 'TOPAGA'),
(null, 5, 'TOTA'),
(null, 5, 'TUNUNGUA'),
(null, 5, 'TURMEQUE'),
(null, 5, 'TUTA'),
(null, 5, 'TUTAZA'),
(null, 5, 'UMBITA'),
(null, 5, 'VENTAQUEMADA'),
(null, 5, 'VIRACACHA'),
(null, 5, 'ZETAQUIRA'),
(null, 6, 'MANIZALES'),
(null, 6, 'AGUADAS'),
(null, 6, 'ANSERMA'),
(null, 6, 'ARANZAZU'),
(null, 6, 'BELALCAZAR'),
(null, 6, 'CHINCHINA'),
(null, 6, 'FILADELFIA'),
(null, 6, 'LA DORADA'),
(null, 6, 'LA MERCED'),
(null, 6, 'MANZANARES'),
(null, 6, 'MARMATO'),
(null, 6, 'MARQUETALIA'),
(null, 6, 'MARULANDA'),
(null, 6, 'NEIRA'),
(null, 6, 'NORCASIA'),
(null, 6, 'PACORA'),
(null, 6, 'PALESTINA'),
(null, 6, 'PENSILVANIA'),
(null, 6, 'RIOSUCIO'),
(null, 6, 'RISARALDA'),
(null, 6, 'SALAMINA'),
(null, 6, 'SAMANA'),
(null, 6, 'SAN JOSE'),
(null, 6, 'SUPIA'),
(null, 6, 'VICTORIA'),
(null, 6, 'VILLAMARIA'),
(null, 6, 'VITERBO'),
(null, 7, 'FLORENCIA'),
(null, 7, 'ALBANIA'),
(null, 7, 'BELEN DE LOS ANDAQUIES'),
(null, 7, 'CARTAGENA DEL CHAIRA'),
(null, 7, 'CURILLO'),
(null, 7, 'EL DONCELLO'),
(null, 7, 'EL PAUJIL'),
(null, 7, 'LA MONTAÑITA'),
(null, 7, 'MILAN'),
(null, 7, 'MORELIA'),
(null, 7, 'PUERTO RICO'),
(null, 7, 'SAN JOSE DEL FRAGUA'),
(null, 7, 'SAN VICENTE DEL CAGUAN'),
(null, 7, 'SOLANO'),
(null, 7, 'SOLITA'),
(null, 7, 'VALPARAISO'),
(null, 8, 'POPAYAN');

INSERT INTO `municipios` (`id`, `departamento_id`, `nombre`) VALUES
(null, 8, 'ALMAGUER'),
(null, 8, 'ARGELIA'),
(null, 8, 'BALBOA'),
(null, 8, 'BOLIVAR'),
(null, 8, 'BUENOS AIRES'),
(null, 8, 'CAJIBIO'),
(null, 8, 'CALDONO'),
(null, 8, 'CALOTO'),
(null, 8, 'CORINTO'),
(null, 8, 'EL TAMBO'),
(null, 8, 'FLORENCIA'),
(null, 8, 'GUACHENE'),
(null, 8, 'GUAPI'),
(null, 8, 'INZA'),
(null, 8, 'JAMBALO'),
(null, 8, 'LA SIERRA'),
(null, 8, 'LA VEGA'),
(null, 8, 'LOPEZ'),
(null, 8, 'MERCADERES'),
(null, 8, 'MIRANDA'),
(null, 8, 'MORALES'),
(null, 8, 'PADILLA'),
(null, 8, 'PAEZ'),
(null, 8, 'PATIA'),
(null, 8, 'PIAMONTE'),
(null, 8, 'PIENDAMO'),
(null, 8, 'PUERTO TEJADA'),
(null, 8, 'PURACE'),
(null, 8, 'ROSAS'),
(null, 8, 'SAN SEBASTIAN'),
(null, 8, 'SANTANDER DE QUILICHAO'),
(null, 8, 'SANTA ROSA'),
(null, 8, 'SILVIA'),
(null, 8, 'SOTARA'),
(null, 8, 'SUAREZ'),
(null, 8, 'SUCRE'),
(null, 8, 'TIMBIO'),
(null, 8, 'TIMBIQUI'),
(null, 8, 'TORIBIO'),
(null, 8, 'TOTORO'),
(null, 8, 'VILLA RICA'),
(null, 9, 'VALLEDUPAR'),
(null, 9, 'AGUACHICA'),
(null, 9, 'AGUSTIN CODAZZI'),
(null, 9, 'ASTREA'),
(null, 9, 'BECERRIL'),
(null, 9, 'BOSCONIA'),
(null, 9, 'CHIMICHAGUA'),
(null, 9, 'CHIRIGUANA'),
(null, 9, 'CURUMANI'),
(null, 9, 'EL COPEY'),
(null, 9, 'EL PASO'),
(null, 9, 'GAMARRA'),
(null, 9, 'GONZALEZ'),
(null, 9, 'LA GLORIA'),
(null, 9, 'LA JAGUA DE IBIRICO'),
(null, 9, 'MANAURE'),
(null, 9, 'PAILITAS'),
(null, 9, 'PELAYA'),
(null, 9, 'PUEBLO BELLO'),
(null, 9, 'RIO DE ORO'),
(null, 9, 'LA PAZ'),
(null, 9, 'SAN ALBERTO'),
(null, 9, 'SAN DIEGO'),
(null, 9, 'SAN MARTIN'),
(null, 9, 'TAMALAMEQUE'),
(null, 10, 'MONTERIA'),
(null, 10, 'AYAPEL'),
(null, 10, 'BUENAVISTA'),
(null, 10, 'CANALETE'),
(null, 10, 'CERETE'),
(null, 10, 'CHIMA'),
(null, 10, 'CHINU'),
(null, 10, 'CIENAGA DE ORO'),
(null, 10, 'COTORRA'),
(null, 10, 'LA APARTADA'),
(null, 10, 'LORICA'),
(null, 10, 'LOS CORDOBAS'),
(null, 10, 'MOMIL'),
(null, 10, 'MONTELIBANO'),
(null, 10, 'MOÑITOS'),
(null, 10, 'PLANETA RICA'),
(null, 10, 'PUEBLO NUEVO'),
(null, 10, 'PUERTO ESCONDIDO'),
(null, 10, 'PUERTO LIBERTADOR'),
(null, 10, 'PURISIMA'),
(null, 10, 'SAHAGUN'),
(null, 10, 'SAN ANDRES SOTAVENTO'),
(null, 10, 'SAN ANTERO'),
(null, 10, 'SAN BERNARDO DEL VIENTO'),
(null, 10, 'SAN CARLOS'),
(null, 10, 'SAN PELAYO'),
(null, 10, 'TIERRALTA'),
(null, 10, 'VALENCIA'),
(null, 11, 'AGUA DE DIOS'),
(null, 11, 'ALBAN'),
(null, 11, 'ANAPOIMA'),
(null, 11, 'ANOLAIMA'),
(null, 11, 'ARBELAEZ'),
(null, 11, 'BELTRAN'),
(null, 11, 'BITUIMA'),
(null, 11, 'BOJACA'),
(null, 11, 'CABRERA'),
(null, 11, 'CACHIPAY'),
(null, 11, 'CAJICA'),
(null, 11, 'CAPARRAPI'),
(null, 11, 'CAQUEZA'),
(null, 11, 'CARMEN DE CARUPA'),
(null, 11, 'CHAGUANI'),
(null, 11, 'CHIA'),
(null, 11, 'CHIPAQUE'),
(null, 11, 'CHOACHI'),
(null, 11, 'CHOCONTA'),
(null, 11, 'COGUA'),
(null, 11, 'COTA'),
(null, 11, 'CUCUNUBA'),
(null, 11, 'EL COLEGIO'),
(null, 11, 'EL PEÑON'),
(null, 11, 'EL ROSAL'),
(null, 11, 'FACATATIVA'),
(null, 11, 'FOMEQUE'),
(null, 11, 'FOSCA'),
(null, 11, 'FUNZA'),
(null, 11, 'FUQUENE'),
(null, 11, 'FUSAGASUGA'),
(null, 11, 'GACHALA'),
(null, 11, 'GACHANCIPA'),
(null, 11, 'GACHETA'),
(null, 11, 'GAMA'),
(null, 11, 'GIRARDOT'),
(null, 11, 'GRANADA'),
(null, 11, 'GUACHETA'),
(null, 11, 'GUADUAS'),
(null, 11, 'GUASCA'),
(null, 11, 'GUATAQUI'),
(null, 11, 'GUATAVITA'),
(null, 11, 'GUAYABAL DE SIQUIMA'),
(null, 11, 'GUAYABETAL'),
(null, 11, 'GUTIERREZ'),
(null, 11, 'JERUSALEN'),
(null, 11, 'JUNIN'),
(null, 11, 'LA CALERA'),
(null, 11, 'LA MESA'),
(null, 11, 'LA PALMA'),
(null, 11, 'LA PEÑA'),
(null, 11, 'LA VEGA'),
(null, 11, 'LENGUAZAQUE'),
(null, 11, 'MACHETA'),
(null, 11, 'MADRID'),
(null, 11, 'MANTA'),
(null, 11, 'MEDINA'),
(null, 11, 'MOSQUERA'),
(null, 11, 'NARIÑO'),
(null, 11, 'NEMOCON'),
(null, 11, 'NILO'),
(null, 11, 'NIMAIMA'),
(null, 11, 'NOCAIMA'),
(null, 11, 'VENECIA'),
(null, 11, 'PACHO'),
(null, 11, 'PAIME'),
(null, 11, 'PANDI'),
(null, 11, 'PARATEBUENO'),
(null, 11, 'PASCA'),
(null, 11, 'PUERTO SALGAR'),
(null, 11, 'PULI'),
(null, 11, 'QUEBRADANEGRA'),
(null, 11, 'QUETAME'),
(null, 11, 'QUIPILE'),
(null, 11, 'APULO'),
(null, 11, 'RICAURTE'),
(null, 11, 'SAN ANTONIO DEL TEQUENDAMA'),
(null, 11, 'SAN BERNARDO'),
(null, 11, 'SAN CAYETANO'),
(null, 11, 'SAN FRANCISCO'),
(null, 11, 'SAN JUAN DE RIO SECO'),
(null, 11, 'SASAIMA'),
(null, 11, 'SESQUILE'),
(null, 11, 'SIBATE'),
(null, 11, 'SILVANIA'),
(null, 11, 'SIMIJACA'),
(null, 11, 'SOACHA'),
(null, 11, 'SOPO'),
(null, 11, 'SUBACHOQUE'),
(null, 11, 'SUESCA'),
(null, 11, 'SUPATA'),
(null, 11, 'SUSA'),
(null, 11, 'SUTATAUSA'),
(null, 11, 'TABIO'),
(null, 11, 'TAUSA'),
(null, 11, 'TENA'),
(null, 11, 'TENJO'),
(null, 11, 'TIBACUY'),
(null, 11, 'TIBIRITA'),
(null, 11, 'TOCAIMA'),
(null, 11, 'TOCANCIPA'),
(null, 11, 'TOPAIPI'),
(null, 11, 'UBALA'),
(null, 11, 'UBAQUE'),
(null, 11, 'VILLA DE SAN DIEGO DE UBATE'),
(null, 11, 'UNE'),
(null, 11, 'UTICA'),
(null, 11, 'VERGARA'),
(null, 11, 'VIANI'),
(null, 11, 'VILLAGOMEZ'),
(null, 11, 'VILLAPINZON'),
(null, 11, 'VILLETA'),
(null, 11, 'VIOTA'),
(null, 11, 'YACOPI'),
(null, 11, 'ZIPACON'),
(null, 11, 'ZIPAQUIRA'),
(null, 12, 'QUIBDO'),
(null, 12, 'ACANDI'),
(null, 12, 'ALTO BAUDO'),
(null, 12, 'ATRATO'),
(null, 12, 'BAGADO'),
(null, 12, 'BAHIA SOLANO'),
(null, 12, 'BAJO BAUDO'),
(null, 12, 'BELEN DE BAJIRA'),
(null, 12, 'BOJAYA'),
(null, 12, 'EL CANTON DEL SAN PABLO'),
(null, 12, 'CARMEN DEL DARIEN'),
(null, 12, 'CERTEGUI'),
(null, 12, 'CONDOTO'),
(null, 12, 'EL CARMEN DE ATRATO'),
(null, 12, 'EL LITORAL DEL SAN JUAN'),
(null, 12, 'ISTMINA'),
(null, 12, 'JURADO'),
(null, 12, 'LLORO'),
(null, 12, 'MEDIO ATRATO'),
(null, 12, 'MEDIO BAUDO'),
(null, 12, 'MEDIO SAN JUAN'),
(null, 12, 'NOVITA'),
(null, 12, 'NUQUI'),
(null, 12, 'RIO IRO'),
(null, 12, 'RIO QUITO'),
(null, 12, 'RIOSUCIO'),
(null, 12, 'SAN JOSE DEL PALMAR'),
(null, 12, 'SIPI'),
(null, 12, 'TADO'),
(null, 12, 'UNGUIA'),
(null, 12, 'UNION PANAMERICANA'),
(null, 13, 'NEIVA'),
(null, 13, 'ACEVEDO'),
(null, 13, 'AGRADO'),
(null, 13, 'AIPE'),
(null, 13, 'ALGECIRAS'),
(null, 13, 'ALTAMIRA'),
(null, 13, 'BARAYA'),
(null, 13, 'CAMPOALEGRE'),
(null, 13, 'COLOMBIA'),
(null, 13, 'ELIAS'),
(null, 13, 'GARZON'),
(null, 13, 'GIGANTE'),
(null, 13, 'GUADALUPE'),
(null, 13, 'HOBO'),
(null, 13, 'IQUIRA'),
(null, 13, 'ISNOS'),
(null, 13, 'LA ARGENTINA'),
(null, 13, 'LA PLATA'),
(null, 13, 'NATAGA'),
(null, 13, 'OPORAPA'),
(null, 13, 'PAICOL'),
(null, 13, 'PALERMO'),
(null, 13, 'PALESTINA'),
(null, 13, 'PITAL'),
(null, 13, 'PITALITO'),
(null, 13, 'RIVERA'),
(null, 13, 'SALADOBLANCO'),
(null, 13, 'SAN AGUSTIN'),
(null, 13, 'SANTA MARIA'),
(null, 13, 'SUAZA'),
(null, 13, 'TARQUI'),
(null, 13, 'TESALIA'),
(null, 13, 'TELLO'),
(null, 13, 'TERUEL'),
(null, 13, 'TIMANA'),
(null, 13, 'VILLAVIEJA'),
(null, 13, 'YAGUARA'),
(null, 14, 'RIOHACHA'),
(null, 14, 'ALBANIA'),
(null, 14, 'BARRANCAS'),
(null, 14, 'DIBULLA'),
(null, 14, 'DISTRACCION'),
(null, 14, 'EL MOLINO'),
(null, 14, 'FONSECA'),
(null, 14, 'HATONUEVO'),
(null, 14, 'LA JAGUA DEL PILAR'),
(null, 14, 'MAICAO'),
(null, 14, 'MANAURE'),
(null, 14, 'SAN JUAN DEL CESAR'),
(null, 14, 'URIBIA'),
(null, 14, 'URUMITA'),
(null, 14, 'VILLANUEVA'),
(null, 15, 'SANTA MARTA'),
(null, 15, 'ALGARROBO'),
(null, 15, 'ARACATACA'),
(null, 15, 'ARIGUANI'),
(null, 15, 'CERRO SAN ANTONIO'),
(null, 15, 'CHIBOLO'),
(null, 15, 'CIENAGA'),
(null, 15, 'CONCORDIA'),
(null, 15, 'EL BANCO'),
(null, 15, 'EL PIÑON'),
(null, 15, 'EL RETEN'),
(null, 15, 'FUNDACION'),
(null, 15, 'GUAMAL'),
(null, 15, 'NUEVA GRANADA'),
(null, 15, 'PEDRAZA'),
(null, 15, 'PIJIÑO DEL CARMEN'),
(null, 15, 'PIVIJAY'),
(null, 15, 'PLATO'),
(null, 15, 'PUEBLOVIEJO'),
(null, 15, 'REMOLINO'),
(null, 15, 'SABANAS DE SAN ANGEL'),
(null, 15, 'SALAMINA'),
(null, 15, 'SAN SEBASTIAN DE BUENAVISTA'),
(null, 15, 'SAN ZENON'),
(null, 15, 'SANTA ANA'),
(null, 15, 'SANTA BARBARA DE PINTO'),
(null, 15, 'SITIONUEVO'),
(null, 15, 'TENERIFE'),
(null, 15, 'ZAPAYAN'),
(null, 15, 'ZONA BANANERA'),
(null, 16, 'VILLAVICENCIO'),
(null, 16, 'ACACIAS'),
(null, 16, 'BARRANCA DE UPIA'),
(null, 16, 'CABUYARO'),
(null, 16, 'CASTILLA LA NUEVA'),
(null, 16, 'CUBARRAL'),
(null, 16, 'CUMARAL'),
(null, 16, 'EL CALVARIO'),
(null, 16, 'EL CASTILLO'),
(null, 16, 'EL DORADO'),
(null, 16, 'FUENTE DE ORO'),
(null, 16, 'GRANADA'),
(null, 16, 'GUAMAL'),
(null, 16, 'MAPIRIPAN'),
(null, 16, 'MESETAS'),
(null, 16, 'LA MACARENA'),
(null, 16, 'URIBE'),
(null, 16, 'LEJANIAS'),
(null, 16, 'PUERTO CONCORDIA'),
(null, 16, 'PUERTO GAITAN'),
(null, 16, 'PUERTO LOPEZ'),
(null, 16, 'PUERTO LLERAS'),
(null, 16, 'PUERTO RICO'),
(null, 16, 'RESTREPO'),
(null, 16, 'SAN CARLOS DE GUAROA'),
(null, 16, 'SAN JUAN DE ARAMA'),
(null, 16, 'SAN JUANITO'),
(null, 16, 'SAN MARTIN'),
(null, 16, 'VISTAHERMOSA'),
(null, 17, 'PASTO'),
(null, 17, 'ALBAN'),
(null, 17, 'ALDANA'),
(null, 17, 'ANCUYA'),
(null, 17, 'ARBOLEDA'),
(null, 17, 'BARBACOAS'),
(null, 17, 'BELEN'),
(null, 17, 'BUESACO'),
(null, 17, 'COLON'),
(null, 17, 'CONSACA'),
(null, 17, 'CONTADERO'),
(null, 17, 'CORDOBA'),
(null, 17, 'CUASPUD'),
(null, 17, 'CUMBAL'),
(null, 17, 'CUMBITARA'),
(null, 17, 'CHACHAGsI'),
(null, 17, 'EL CHARCO'),
(null, 17, 'EL PEÑOL'),
(null, 17, 'EL ROSARIO'),
(null, 17, 'EL TABLON DE GOMEZ'),
(null, 17, 'EL TAMBO'),
(null, 17, 'FUNES'),
(null, 17, 'GUACHUCAL'),
(null, 17, 'GUAITARILLA'),
(null, 17, 'GUALMATAN'),
(null, 17, 'ILES'),
(null, 17, 'IMUES'),
(null, 17, 'IPIALES'),
(null, 17, 'LA CRUZ'),
(null, 17, 'LA FLORIDA'),
(null, 17, 'LA LLANADA'),
(null, 17, 'LA TOLA'),
(null, 17, 'LA UNION'),
(null, 17, 'LEIVA'),
(null, 17, 'LINARES'),
(null, 17, 'LOS ANDES'),
(null, 17, 'MAGsI'),
(null, 17, 'MALLAMA'),
(null, 17, 'MOSQUERA'),
(null, 17, 'NARIÑO'),
(null, 17, 'OLAYA HERRERA'),
(null, 17, 'OSPINA'),
(null, 17, 'FRANCISCO PIZARRO'),
(null, 17, 'POLICARPA'),
(null, 17, 'POTOSI'),
(null, 17, 'PROVIDENCIA'),
(null, 17, 'PUERRES'),
(null, 17, 'PUPIALES');

INSERT INTO `municipios` (`id`, `departamento_id`, `nombre`) VALUES
(null, 17, 'RICAURTE'),
(null, 17, 'ROBERTO PAYAN'),
(null, 17, 'SAMANIEGO'),
(null, 17, 'SANDONA'),
(null, 17, 'SAN BERNARDO'),
(null, 17, 'SAN LORENZO'),
(null, 17, 'SAN PABLO'),
(null, 17, 'SAN PEDRO DE CARTAGO'),
(null, 17, 'SANTA BARBARA'),
(null, 17, 'SANTACRUZ'),
(null, 17, 'SAPUYES'),
(null, 17, 'TAMINANGO'),
(null, 17, 'TANGUA'),
(null, 17, 'SAN ANDRES DE TUMACO'),
(null, 17, 'TUQUERRES'),
(null, 17, 'YACUANQUER'),
(null, 18, 'CUCUTA'),
(null, 18, 'ABREGO'),
(null, 18, 'ARBOLEDAS'),
(null, 18, 'BOCHALEMA'),
(null, 18, 'BUCARASICA'),
(null, 18, 'CACOTA'),
(null, 18, 'CACHIRA'),
(null, 18, 'CHINACOTA'),
(null, 18, 'CHITAGA'),
(null, 18, 'CONVENCION'),
(null, 18, 'CUCUTILLA'),
(null, 18, 'DURANIA'),
(null, 18, 'EL CARMEN'),
(null, 18, 'EL TARRA'),
(null, 18, 'EL ZULIA'),
(null, 18, 'GRAMALOTE'),
(null, 18, 'HACARI'),
(null, 18, 'HERRAN'),
(null, 18, 'LABATECA'),
(null, 18, 'LA ESPERANZA'),
(null, 18, 'LA PLAYA'),
(null, 18, 'LOS PATIOS'),
(null, 18, 'LOURDES'),
(null, 18, 'MUTISCUA'),
(null, 18, 'OCAÑA'),
(null, 18, 'PAMPLONA'),
(null, 18, 'PAMPLONITA'),
(null, 18, 'PUERTO SANTANDER'),
(null, 18, 'RAGONVALIA'),
(null, 18, 'SALAZAR'),
(null, 18, 'SAN CALIXTO'),
(null, 18, 'SAN CAYETANO'),
(null, 18, 'SANTIAGO'),
(null, 18, 'SARDINATA'),
(null, 18, 'SILOS'),
(null, 18, 'TEORAMA'),
(null, 18, 'TIBU'),
(null, 18, 'TOLEDO'),
(null, 18, 'VILLA CARO'),
(null, 18, 'VILLA DEL ROSARIO'),
(null, 19, 'ARMENIA'),
(null, 19, 'BUENAVISTA'),
(null, 19, 'CALARCA'),
(null, 19, 'CIRCASIA'),
(null, 19, 'CORDOBA'),
(null, 19, 'FILANDIA'),
(null, 19, 'GENOVA'),
(null, 19, 'LA TEBAIDA'),
(null, 19, 'MONTENEGRO'),
(null, 19, 'PIJAO'),
(null, 19, 'QUIMBAYA'),
(null, 19, 'SALENTO'),
(null, 20, 'PEREIRA'),
(null, 20, 'APIA'),
(null, 20, 'BALBOA'),
(null, 20, 'BELEN DE UMBRIA'),
(null, 20, 'DOSQUEBRADAS'),
(null, 20, 'GUATICA'),
(null, 20, 'LA CELIA'),
(null, 20, 'LA VIRGINIA'),
(null, 20, 'MARSELLA'),
(null, 20, 'MISTRATO'),
(null, 20, 'PUEBLO RICO'),
(null, 20, 'QUINCHIA'),
(null, 20, 'SANTA ROSA DE CABAL'),
(null, 20, 'SANTUARIO'),
(null, 21, 'BUCARAMANGA'),
(null, 21, 'AGUADA'),
(null, 21, 'ALBANIA'),
(null, 21, 'ARATOCA'),
(null, 21, 'BARBOSA'),
(null, 21, 'BARICHARA'),
(null, 21, 'BARRANCABERMEJA'),
(null, 21, 'BETULIA'),
(null, 21, 'BOLIVAR'),
(null, 21, 'CABRERA'),
(null, 21, 'CALIFORNIA'),
(null, 21, 'CAPITANEJO'),
(null, 21, 'CARCASI'),
(null, 21, 'CEPITA'),
(null, 21, 'CERRITO'),
(null, 21, 'CHARALA'),
(null, 21, 'CHARTA'),
(null, 21, 'CHIMA'),
(null, 21, 'CHIPATA'),
(null, 21, 'CIMITARRA'),
(null, 21, 'CONCEPCION'),
(null, 21, 'CONFINES'),
(null, 21, 'CONTRATACION'),
(null, 21, 'COROMORO'),
(null, 21, 'CURITI'),
(null, 21, 'EL CARMEN DE CHUCURI'),
(null, 21, 'EL GUACAMAYO'),
(null, 21, 'EL PEÑON'),
(null, 21, 'EL PLAYON'),
(null, 21, 'ENCINO'),
(null, 21, 'ENCISO'),
(null, 21, 'FLORIAN'),
(null, 21, 'FLORIDABLANCA'),
(null, 21, 'GALAN'),
(null, 21, 'GAMBITA'),
(null, 21, 'GIRON'),
(null, 21, 'GUACA'),
(null, 21, 'GUADALUPE'),
(null, 21, 'GUAPOTA'),
(null, 21, 'GUAVATA'),
(null, 21, 'GsEPSA'),
(null, 21, 'HATO'),
(null, 21, 'JESUS MARIA'),
(null, 21, 'JORDAN'),
(null, 21, 'LA BELLEZA'),
(null, 21, 'LANDAZURI'),
(null, 21, 'LA PAZ'),
(null, 21, 'LEBRIJA'),
(null, 21, 'LOS SANTOS'),
(null, 21, 'MACARAVITA'),
(null, 21, 'MALAGA'),
(null, 21, 'MATANZA'),
(null, 21, 'MOGOTES'),
(null, 21, 'MOLAGAVITA'),
(null, 21, 'OCAMONTE'),
(null, 21, 'OIBA'),
(null, 21, 'ONZAGA'),
(null, 21, 'PALMAR'),
(null, 21, 'PALMAS DEL SOCORRO'),
(null, 21, 'PARAMO'),
(null, 21, 'PIEDECUESTA'),
(null, 21, 'PINCHOTE'),
(null, 21, 'PUENTE NACIONAL'),
(null, 21, 'PUERTO PARRA'),
(null, 21, 'PUERTO WILCHES'),
(null, 21, 'RIONEGRO'),
(null, 21, 'SABANA DE TORRES'),
(null, 21, 'SAN ANDRES'),
(null, 21, 'SAN BENITO'),
(null, 21, 'SAN GIL'),
(null, 21, 'SAN JOAQUIN'),
(null, 21, 'SAN JOSE DE MIRANDA'),
(null, 21, 'SAN MIGUEL'),
(null, 21, 'SAN VICENTE DE CHUCURI'),
(null, 21, 'SANTA BARBARA'),
(null, 21, 'SANTA HELENA DEL OPON'),
(null, 21, 'SIMACOTA'),
(null, 21, 'SOCORRO'),
(null, 21, 'SUAITA'),
(null, 21, 'SUCRE'),
(null, 21, 'SURATA'),
(null, 21, 'TONA'),
(null, 21, 'VALLE DE SAN JOSE'),
(null, 21, 'VELEZ'),
(null, 21, 'VETAS'),
(null, 21, 'VILLANUEVA'),
(null, 21, 'ZAPATOCA'),
(null, 22, 'SINCELEJO'),
(null, 22, 'BUENAVISTA'),
(null, 22, 'CAIMITO'),
(null, 22, 'COLOSO'),
(null, 22, 'COROZAL'),
(null, 22, 'COVEÑAS'),
(null, 22, 'CHALAN'),
(null, 22, 'EL ROBLE'),
(null, 22, 'GALERAS'),
(null, 22, 'GUARANDA'),
(null, 22, 'LA UNION'),
(null, 22, 'LOS PALMITOS'),
(null, 22, 'MAJAGUAL'),
(null, 22, 'MORROA'),
(null, 22, 'OVEJAS'),
(null, 22, 'PALMITO'),
(null, 22, 'SAMPUES'),
(null, 22, 'SAN BENITO ABAD'),
(null, 22, 'SAN JUAN DE BETULIA'),
(null, 22, 'SAN MARCOS'),
(null, 22, 'SAN ONOFRE'),
(null, 22, 'SAN PEDRO'),
(null, 22, 'SAN LUIS DE SINCE'),
(null, 22, 'SUCRE'),
(null, 22, 'SANTIAGO DE TOLU'),
(null, 22, 'TOLU VIEJO'),
(null, 23, 'IBAGUE'),
(null, 23, 'ALPUJARRA'),
(null, 23, 'ALVARADO'),
(null, 23, 'AMBALEMA'),
(null, 23, 'ANZOATEGUI'),
(null, 23, 'ARMERO'),
(null, 23, 'ATACO'),
(null, 23, 'CAJAMARCA'),
(null, 23, 'CARMEN DE APICALA'),
(null, 23, 'CASABIANCA'),
(null, 23, 'CHAPARRAL'),
(null, 23, 'COELLO'),
(null, 23, 'COYAIMA'),
(null, 23, 'CUNDAY'),
(null, 23, 'DOLORES'),
(null, 23, 'ESPINAL'),
(null, 23, 'FALAN'),
(null, 23, 'FLANDES'),
(null, 23, 'FRESNO'),
(null, 23, 'GUAMO'),
(null, 23, 'HERVEO'),
(null, 23, 'HONDA'),
(null, 23, 'ICONONZO'),
(null, 23, 'LERIDA'),
(null, 23, 'LIBANO'),
(null, 23, 'MARIQUITA'),
(null, 23, 'MELGAR'),
(null, 23, 'MURILLO'),
(null, 23, 'NATAGAIMA'),
(null, 23, 'ORTEGA'),
(null, 23, 'PALOCABILDO'),
(null, 23, 'PIEDRAS'),
(null, 23, 'PLANADAS'),
(null, 23, 'PRADO'),
(null, 23, 'PURIFICACION'),
(null, 23, 'RIOBLANCO'),
(null, 23, 'RONCESVALLES'),
(null, 23, 'ROVIRA'),
(null, 23, 'SALDAÑA'),
(null, 23, 'SAN ANTONIO'),
(null, 23, 'SAN LUIS'),
(null, 23, 'SANTA ISABEL'),
(null, 23, 'SUAREZ'),
(null, 23, 'VALLE DE SAN JUAN'),
(null, 23, 'VENADILLO'),
(null, 23, 'VILLAHERMOSA'),
(null, 23, 'VILLARRICA'),
(null, 24, 'CALI'),
(null, 24, 'ALCALA'),
(null, 24, 'ANDALUCIA'),
(null, 24, 'ANSERMANUEVO'),
(null, 24, 'ARGELIA'),
(null, 24, 'BOLIVAR'),
(null, 24, 'BUENAVENTURA'),
(null, 24, 'GUADALAJARA DE BUGA'),
(null, 24, 'BUGALAGRANDE'),
(null, 24, 'CAICEDONIA'),
(null, 24, 'CALIMA'),
(null, 24, 'CANDELARIA'),
(null, 24, 'CARTAGO'),
(null, 24, 'DAGUA'),
(null, 24, 'EL AGUILA'),
(null, 24, 'EL CAIRO'),
(null, 24, 'EL CERRITO'),
(null, 24, 'EL DOVIO'),
(null, 24, 'FLORIDA'),
(null, 24, 'GINEBRA'),
(null, 24, 'GUACARI'),
(null, 24, 'JAMUNDI'),
(null, 24, 'LA CUMBRE'),
(null, 24, 'LA UNION'),
(null, 24, 'LA VICTORIA'),
(null, 24, 'OBANDO'),
(null, 24, 'PALMIRA'),
(null, 24, 'PRADERA'),
(null, 24, 'RESTREPO'),
(null, 24, 'RIOFRIO'),
(null, 24, 'ROLDANILLO'),
(null, 24, 'SAN PEDRO'),
(null, 24, 'SEVILLA'),
(null, 24, 'TORO'),
(null, 24, 'TRUJILLO'),
(null, 24, 'TULUA'),
(null, 24, 'ULLOA'),
(null, 24, 'VERSALLES'),
(null, 24, 'VIJES'),
(null, 24, 'YOTOCO'),
(null, 24, 'YUMBO'),
(null, 24, 'ZARZAL'),
(null, 25, 'ARAUCA'),
(null, 25, 'ARAUQUITA'),
(null, 25, 'CRAVO NORTE'),
(null, 25, 'FORTUL'),
(null, 25, 'PUERTO RONDON'),
(null, 25, 'SARAVENA'),
(null, 25, 'TAME'),
(null, 26, 'YOPAL'),
(null, 26, 'AGUAZUL'),
(null, 26, 'CHAMEZA'),
(null, 26, 'HATO COROZAL'),
(null, 26, 'LA SALINA'),
(null, 26, 'MANI'),
(null, 26, 'MONTERREY'),
(null, 26, 'NUNCHIA'),
(null, 26, 'OROCUE'),
(null, 26, 'PAZ DE ARIPORO'),
(null, 26, 'PORE'),
(null, 26, 'RECETOR'),
(null, 26, 'SABANALARGA'),
(null, 26, 'SACAMA'),
(null, 26, 'SAN LUIS DE PALENQUE'),
(null, 26, 'TAMARA'),
(null, 26, 'TAURAMENA'),
(null, 26, 'TRINIDAD'),
(null, 26, 'VILLANUEVA'),
(null, 27, 'MOCOA'),
(null, 27, 'COLON'),
(null, 27, 'ORITO'),
(null, 27, 'PUERTO ASIS'),
(null, 27, 'PUERTO CAICEDO'),
(null, 27, 'PUERTO GUZMAN'),
(null, 27, 'LEGUIZAMO'),
(null, 27, 'SIBUNDOY'),
(null, 27, 'SAN FRANCISCO'),
(null, 27, 'SAN MIGUEL'),
(null, 27, 'SANTIAGO'),
(null, 27, 'VALLE DEL GUAMUEZ'),
(null, 27, 'VILLAGARZON'),
(null, 28, 'SAN ANDRES'),
(null, 28, 'PROVIDENCIA'),
(null, 29, 'LETICIA'),
(null, 29, 'EL ENCANTO'),
(null, 29, 'LA CHORRERA'),
(null, 29, 'LA PEDRERA'),
(null, 29, 'LA VICTORIA'),
(null, 29, 'MIRITI - PARANA'),
(null, 29, 'PUERTO ALEGRIA'),
(null, 29, 'PUERTO ARICA'),
(null, 29, 'PUERTO NARIÑO'),
(null, 29, 'PUERTO SANTANDER'),
(null, 29, 'TARAPACA'),
(null, 30, 'INIRIDA'),
(null, 30, 'BARRANCO MINAS'),
(null, 30, 'MAPIRIPANA'),
(null, 30, 'SAN FELIPE'),
(null, 30, 'PUERTO COLOMBIA'),
(null, 30, 'LA GUADALUPE'),
(null, 30, 'CACAHUAL'),
(null, 30, 'PANA PANA'),
(null, 30, 'MORICHAL'),
(null, 31, 'SAN JOSE DEL GUAVIARE'),
(null, 31, 'CALAMAR'),
(null, 31, 'EL RETORNO'),
(null, 31, 'MIRAFLORES'),
(null, 32, 'MITU'),
(null, 32, 'CARURU'),
(null, 32, 'PACOA'),
(null, 32, 'TARAIRA'),
(null, 32, 'PAPUNAUA'),
(null, 32, 'YAVARATE'),
(null, 33, 'PUERTO CARREÑO'),
(null, 33, 'LA PRIMAVERA'),
(null, 33, 'SANTA ROSALIA'),
(null, 33, 'CUMARIBO');






